// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "sentencepiece",
    products: [
        .library(
            name: "sentencepiece",
            targets: ["sentencepiece"]
        ),
        .executable(name: "spm_encode", targets: ["spm_encode"]),
        .executable(name: "spm_decode", targets: ["spm_decode"]),
        .executable(name: "spm_normalize", targets: ["spm_normalize"]),
        .executable(name: "spm_train", targets: ["spm_train"]),
        .executable(name: "spm_export_vocab", targets: ["spm_export_vocab"]),
    ],
    targets: [
        .target(
            name: "sentencepiece",
            path: ".",
            exclude: [
                "python",
                "doc",
                "data",
                "cmake",
                "contrib",
                ".github",
                // Test files
                "src/bpe_model_test.cc",
                "src/bpe_model_trainer_test.cc",
                "src/builder_test.cc",
                "src/char_model_test.cc",
                "src/char_model_trainer_test.cc",
                "src/filesystem_test.cc",
                "src/freelist_test.cc",
                "src/init_test.cc",
                "src/model_factory_test.cc",
                "src/model_interface_test.cc",
                "src/normalizer_test.cc",
                "src/sentencepiece_processor_test.cc",
                "src/sentencepiece_trainer_test.cc",
                "src/test_main.cc",
                "src/testharness.cc",
                "src/trainer_factory_test.cc",
                "src/trainer_interface_test.cc",
                "src/unicode_script_test.cc",
                "src/unigram_model_test.cc",
                "src/unigram_model_trainer_test.cc",
                "src/util_test.cc",
                "src/word_model_test.cc",
                "src/word_model_trainer_test.cc",
                "src/pretokenizer_for_training_test.cc",
                // Executable main files
                "src/spm_encode_main.cc",
                "src/spm_decode_main.cc",
                "src/spm_normalize_main.cc",
                "src/spm_train_main.cc",
                "src/spm_export_vocab_main.cc",
                "src/compile_charsmap_main.cc",
                // Proto source files (not C++)
                "src/sentencepiece.proto",
                "src/sentencepiece_model.proto",
            ],
            sources: [
                // Core sentencepiece
                "src/bpe_model.cc",
                "src/char_model.cc",
                "src/error.cc",
                "src/filesystem.cc",
                "src/init.cc",
                "src/model_factory.cc",
                "src/model_interface.cc",
                "src/normalizer.cc",
                "src/sentencepiece_processor.cc",
                "src/unigram_model.cc",
                "src/util.cc",
                "src/word_model.cc",
                // Training
                "src/builder.cc",
                "src/unicode_script.cc",
                "src/trainer_factory.cc",
                "src/trainer_interface.cc",
                "src/unigram_model_trainer.cc",
                "src/word_model_trainer.cc",
                "src/char_model_trainer.cc",
                "src/bpe_model_trainer.cc",
                "src/sentencepiece_trainer.cc",
                "src/pretokenizer_for_training.cc",
                // Builtin protobuf
                "src/builtin_pb/sentencepiece.pb.cc",
                "src/builtin_pb/sentencepiece_model.pb.cc",
                // Internal protobuf-lite
                "third_party/protobuf-lite/arena.cc",
                "third_party/protobuf-lite/arenastring.cc",
                "third_party/protobuf-lite/bytestream.cc",
                "third_party/protobuf-lite/coded_stream.cc",
                "third_party/protobuf-lite/common.cc",
                "third_party/protobuf-lite/extension_set.cc",
                "third_party/protobuf-lite/generated_enum_util.cc",
                "third_party/protobuf-lite/generated_message_table_driven_lite.cc",
                "third_party/protobuf-lite/generated_message_util.cc",
                "third_party/protobuf-lite/implicit_weak_message.cc",
                "third_party/protobuf-lite/int128.cc",
                "third_party/protobuf-lite/io_win32.cc",
                "third_party/protobuf-lite/message_lite.cc",
                "third_party/protobuf-lite/parse_context.cc",
                "third_party/protobuf-lite/repeated_field.cc",
                "third_party/protobuf-lite/status.cc",
                "third_party/protobuf-lite/statusor.cc",
                "third_party/protobuf-lite/stringpiece.cc",
                "third_party/protobuf-lite/stringprintf.cc",
                "third_party/protobuf-lite/structurally_valid.cc",
                "third_party/protobuf-lite/strutil.cc",
                "third_party/protobuf-lite/time.cc",
                "third_party/protobuf-lite/wire_format_lite.cc",
                "third_party/protobuf-lite/zero_copy_stream.cc",
                "third_party/protobuf-lite/zero_copy_stream_impl.cc",
                "third_party/protobuf-lite/zero_copy_stream_impl_lite.cc",
                // Internal absl
                "third_party/absl/flags/flag.cc",
                "third_party/absl/log/log.cc",
            ],
            publicHeadersPath: "include",
            cxxSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("src"),
                .headerSearchPath("src/builtin_pb"),
                .headerSearchPath("third_party"),
                .headerSearchPath("third_party/protobuf-lite"),
                .headerSearchPath("third_party/absl"),
                .headerSearchPath("."),
                .define("HAVE_PTHREAD", to: "1"),
                .unsafeFlags([
                    "-Wno-sign-compare",
                    "-Wno-deprecated-declarations",
                    "-Wno-shorten-64-to-32",
                    "-Wno-comma",
                    "-Wno-unused-parameter",
                ]),
            ]
        ),
        // Executable targets
        .executableTarget(
            name: "spm_encode",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: ["spm_encode_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_decode",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: ["spm_decode_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_normalize",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: ["spm_normalize_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_train",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: ["spm_train_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        .executableTarget(
            name: "spm_export_vocab",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: ["spm_export_vocab_main.cc"],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
            ]
        ),
        // Test target
        .executableTarget(
            name: "spm_test",
            dependencies: ["sentencepiece"],
            path: "src",
            sources: [
                "test_main.cc",
                "testharness.cc",
                "bpe_model_test.cc",
                "bpe_model_trainer_test.cc",
                "builder_test.cc",
                "char_model_test.cc",
                "char_model_trainer_test.cc",
                "filesystem_test.cc",
                "freelist_test.cc",
                "init_test.cc",
                "model_factory_test.cc",
                "model_interface_test.cc",
                "normalizer_test.cc",
                "sentencepiece_processor_test.cc",
                "sentencepiece_trainer_test.cc",
                "trainer_factory_test.cc",
                "trainer_interface_test.cc",
                "unicode_script_test.cc",
                "unigram_model_test.cc",
                "unigram_model_trainer_test.cc",
                "util_test.cc",
                "word_model_test.cc",
                "word_model_trainer_test.cc",
                "pretokenizer_for_training_test.cc",
            ],
            cxxSettings: [
                .headerSearchPath("."),
                .headerSearchPath("builtin_pb"),
                .headerSearchPath(".."),
                .headerSearchPath("../third_party"),
                .headerSearchPath("../third_party/protobuf-lite"),
                .headerSearchPath("../third_party/absl"),
                .define("HAVE_PTHREAD", to: "1"),
                .unsafeFlags(["-Wno-sign-compare"]),
            ]
        ),
    ],
    cxxLanguageStandard: .cxx17
)
